version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:light
    steps:
      - setup_remote_docker
      - run:
          name: "packer build"
          command: "packer build docker.json"
