version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - restore_cache:
          key: "packer-1.1.2"
      - run:
          name: "install packer"
          command: ./install_packer.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - "~/bin"
      - setup_remote_docker
      - run:
          name: "packer build"
          command: "packer build docker.json"
